# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.network "forwarded_port", guest: 80, host: 4567, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 5000, host: 4568, host_ip: "127.0.0.1"
  config.vm.synced_folder "www", "/var/www"
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y apache2
    apt-get install -y curl
    echo "#!/bin/bash
    function InstallPip {
      if [ '$(which pip)' ]; then
        echo '-- Already installed.'
        return
      fi
      apt-get install python-dev python-setuptools -y -qq
      apt-get install -y python-pip
      pip install --upgrade pip
      apt-get install -y mongodb
      apt-get install -y python-pymongo
      apt-get install -y python-bson
    }
    echo 'Installing Pip...'; InstallPip
    echo 'Installing Flask...'; pip install flask
    echo 'Installing requests...'; pip install requests
    echo 'Installing flask_cors...'; pip install flask_cors
    exit 0" | /bin/bash
  SHELL
end
